export let engFilter = [
    {name:'타격의 대가',grade:"전설",level:0,finalDamagePer:1.13, engBonus:0},
    {name:'타격의 대가',grade:"전설",level:1,finalDamagePer:1.1375, engBonus:0},
    {name:'타격의 대가',grade:"전설",level:2,finalDamagePer:1.145,  engBonus:0},
    {name:'타격의 대가',grade:"전설",level:3,finalDamagePer:1.1525, engBonus:0},
    {name:'타격의 대가',grade:"유물",level:0,finalDamagePer:1.16, engBonus:0},
    {name:'타격의 대가',grade:"유물",level:1,finalDamagePer:1.1675, engBonus:0},
    {name:'타격의 대가',grade:"유물",level:2,finalDamagePer:1.175,  engBonus:0},
    {name:'타격의 대가',grade:"유물",level:3,finalDamagePer:1.1825, engBonus:0},
    {name:'타격의 대가',grade:"유물",level:4,finalDamagePer:1.19, engBonus:0},

    {name:'결투의 대가',grade:"전설",level:0,finalDamagePer:1.13, engBonus:0},   
    {name:'결투의 대가',grade:"전설",level:1,finalDamagePer:1.1375, engBonus:0},
    {name:'결투의 대가',grade:"전설",level:2,finalDamagePer:1.145, engBonus:0},
    {name:'결투의 대가',grade:"전설",level:3,finalDamagePer:1.1525, engBonus:0},
    {name:'결투의 대가',grade:"유물",level:0,finalDamagePer:1.16, engBonus:0},
    {name:'결투의 대가',grade:"유물",level:1,finalDamagePer:1.1675, engBonus:0},
    {name:'결투의 대가',grade:"유물",level:2,finalDamagePer:1.175, engBonus:0},
    {name:'결투의 대가',grade:"유물",level:3,finalDamagePer:1.1825, engBonus:0},
    {name:'결투의 대가',grade:"유물",level:4,finalDamagePer:1.19, engBonus:0},

    {name:'기습의 대가',grade:"전설",level:0,finalDamagePer:1.13, engBonus:0},  
    {name:'기습의 대가',grade:"전설",level:1,finalDamagePer:1.1375, engBonus:0},         
    {name:'기습의 대가',grade:"전설",level:2,finalDamagePer:1.145, engBonus:0},
    {name:'기습의 대가',grade:"전설",level:3,finalDamagePer:1.1525, engBonus:0},
    {name:'기습의 대가',grade:"유물",level:0,finalDamagePer:1.16, engBonus:0},
    {name:'기습의 대가',grade:"유물",level:1,finalDamagePer:1.1675, engBonus:0},
    {name:'기습의 대가',grade:"유물",level:2,finalDamagePer:1.175, engBonus:0},
    {name:'기습의 대가',grade:"유물",level:3,finalDamagePer:1.1825, engBonus:0},
    {name:'기습의 대가',grade:"유물",level:4,finalDamagePer:1.19, engBonus:0},

    {name:'달인의 저력',grade:"전설",level:0,finalDamagePer:1.13, engBonus:0},
    {name:'달인의 저력',grade:"전설",level:1,finalDamagePer:1.1375, engBonus:0},
    {name:'달인의 저력',grade:"전설",level:2,finalDamagePer:1.145, engBonus:0},
    {name:'달인의 저력',grade:"전설",level:3,finalDamagePer:1.1525, engBonus:0},
    {name:'달인의 저력',grade:"유물",level:0,finalDamagePer:1.16, engBonus:0},
    {name:'달인의 저력',grade:"유물",level:1,finalDamagePer:1.1675, engBonus:0},
    {name:'달인의 저력',grade:"유물",level:2,finalDamagePer:1.175, engBonus:0},
    {name:'달인의 저력',grade:"유물",level:3,finalDamagePer:1.1825, engBonus:0},
    {name:'달인의 저력',grade:"유물",level:4,finalDamagePer:1.19, engBonus:0},

    {name:'돌격대장',grade:"전설",level:0,finalDamagePer:1.13, engBonus:0},
    {name:'돌격대장',grade:"전설",level:1,finalDamagePer:1.1375, engBonus:0},
    {name:'돌격대장',grade:"전설",level:2,finalDamagePer:1.145, engBonus:0},
    {name:'돌격대장',grade:"전설",level:3,finalDamagePer:1.1525, engBonus:0},
    {name:'돌격대장',grade:"유물",level:0,finalDamagePer:1.16, engBonus:0},
    {name:'돌격대장',grade:"유물",level:1,finalDamagePer:1.1675, engBonus:0},
    {name:'돌격대장',grade:"유물",level:2,finalDamagePer:1.175, engBonus:0},
    {name:'돌격대장',grade:"유물",level:3,finalDamagePer:1.1825, engBonus:0},
    {name:'돌격대장',grade:"유물",level:4,finalDamagePer:1.19, engBonus:0},

    {name:'마나 효율 증가',grade:"전설",level:0,finalDamagePer:1.13, engBonus:0},
    {name:'마나 효율 증가',grade:"전설",level:1,finalDamagePer:1.1375, engBonus:0},
    {name:'마나 효율 증가',grade:"전설",level:2,finalDamagePer:1.145, engBonus:0},
    {name:'마나 효율 증가',grade:"전설",level:3,finalDamagePer:1.1525, engBonus:0},
    {name:'마나 효율 증가',grade:"유물",level:0,finalDamagePer:1.16, engBonus:0},
    {name:'마나 효율 증가',grade:"유물",level:1,finalDamagePer:1.1675, engBonus:0},
    {name:'마나 효율 증가',grade:"유물",level:2,finalDamagePer:1.175, engBonus:0},
    {name:'마나 효율 증가',grade:"유물",level:3,finalDamagePer:1.1825, engBonus:0},
    {name:'마나 효율 증가',grade:"유물",level:4,finalDamagePer:1.19, engBonus:0},

    {name:'바리케이드',grade:"전설",level:0,finalDamagePer:1.13, engBonus:0},
    {name:'바리케이드',grade:"전설",level:1,finalDamagePer:1.1375, engBonus:0},
    {name:'바리케이드',grade:"전설",level:2,finalDamagePer:1.145, engBonus:0},
    {name:'바리케이드',grade:"전설",level:3,finalDamagePer:1.1525, engBonus:0},
    {name:'바리케이드',grade:"유물",level:0,finalDamagePer:1.16, engBonus:0},
    {name:'바리케이드',grade:"유물",level:1,finalDamagePer:1.1675, engBonus:0},
    {name:'바리케이드',grade:"유물",level:2,finalDamagePer:1.175, engBonus:0},
    {name:'바리케이드',grade:"유물",level:3,finalDamagePer:1.1825, engBonus:0},
    {name:'바리케이드',grade:"유물",level:4,finalDamagePer:1.19, engBonus:0},

    {name:'속전속결',grade:"전설",level:0,finalDamagePer:1.13, engBonus:0},
    {name:'속전속결',grade:"전설",level:1,finalDamagePer:1.1375, engBonus:0},
    {name:'속전속결',grade:"전설",level:2,finalDamagePer:1.145, engBonus:0},
    {name:'속전속결',grade:"전설",level:3,finalDamagePer:1.1525, engBonus:0},
    {name:'속전속결',grade:"유물",level:0,finalDamagePer:1.16, engBonus:0},
    {name:'속전속결',grade:"유물",level:1,finalDamagePer:1.1675, engBonus:0},
    {name:'속전속결',grade:"유물",level:2,finalDamagePer:1.175, engBonus:0},
    {name:'속전속결',grade:"유물",level:3,finalDamagePer:1.1825, engBonus:0},
    {name:'속전속결',grade:"유물",level:4,finalDamagePer:1.19, engBonus:0},

    {name:'슈퍼 차지',grade:"전설",level:0,finalDamagePer:1.13, engBonus:0},
    {name:'슈퍼 차지',grade:"전설",level:1,finalDamagePer:1.1375, engBonus:0},
    {name:'슈퍼 차지',grade:"전설",level:2,finalDamagePer:1.145, engBonus:0},
    {name:'슈퍼 차지',grade:"전설",level:3,finalDamagePer:1.1525, engBonus:0},
    {name:'슈퍼 차지',grade:"유물",level:0,finalDamagePer:1.16, engBonus:0},
    {name:'슈퍼 차지',grade:"유물",level:1,finalDamagePer:1.1675, engBonus:0},
    {name:'슈퍼 차지',grade:"유물",level:2,finalDamagePer:1.175, engBonus:0},
    {name:'슈퍼 차지',grade:"유물",level:3,finalDamagePer:1.1825, engBonus:0},
    {name:'슈퍼 차지',grade:"유물",level:4,finalDamagePer:1.19, engBonus:0},

    {name:'아드레날린',grade:"전설",level:0,finalDamagePer:1.13, engBonus:0},
    {name:'아드레날린',grade:"전설",level:1,finalDamagePer:1.1375, engBonus:0},
    {name:'아드레날린',grade:"전설",level:2,finalDamagePer:1.145, engBonus:0},
    {name:'아드레날린',grade:"전설",level:3,finalDamagePer:1.1525, engBonus:0},
    {name:'아드레날린',grade:"유물",level:0,finalDamagePer:1.16, engBonus:0},
    {name:'아드레날린',grade:"유물",level:1,finalDamagePer:1.1675, engBonus:0},
    {name:'아드레날린',grade:"유물",level:2,finalDamagePer:1.175, engBonus:0},
    {name:'아드레날린',grade:"유물",level:3,finalDamagePer:1.1825, engBonus:0},
    {name:'아드레날린',grade:"유물",level:4,finalDamagePer:1.19, engBonus:0},

    {name:'안정된 상태',grade:"전설",level:0,finalDamagePer:1.13, engBonus:0},
    {name:'안정된 상태',grade:"전설",level:1,finalDamagePer:1.1375, engBonus:0},
    {name:'안정된 상태',grade:"전설",level:2,finalDamagePer:1.145, engBonus:0},
    {name:'안정된 상태',grade:"전설",level:3,finalDamagePer:1.1525, engBonus:0},
    {name:'안정된 상태',grade:"유물",level:0,finalDamagePer:1.16, engBonus:0},
    {name:'안정된 상태',grade:"유물",level:1,finalDamagePer:1.1675, engBonus:0},
    {name:'안정된 상태',grade:"유물",level:2,finalDamagePer:1.175, engBonus:0},
    {name:'안정된 상태',grade:"유물",level:3,finalDamagePer:1.1825, engBonus:0},
    {name:'안정된 상태',grade:"유물",level:4,finalDamagePer:1.19, engBonus:0},

    {name:'에테르 포식자',grade:"전설",level:0,finalDamagePer:1.1131, engBonus:0},
    {name:'에테르 포식자',grade:"전설",level:1,finalDamagePer:1.1225, engBonus:0},
    {name:'에테르 포식자',grade:"전설",level:2,finalDamagePer:1.1323, engBonus:0},
    {name:'에테르 포식자',grade:"전설",level:3,finalDamagePer:1.1423, engBonus:0},
    {name:'에테르 포식자',grade:"유물",level:0,finalDamagePer:1.1538, engBonus:0},
    {name:'에테르 포식자',grade:"유물",level:1,finalDamagePer:1.1611, engBonus:0},
    {name:'에테르 포식자',grade:"유물",level:2,finalDamagePer:1.1682, engBonus:0},
    {name:'에테르 포식자',grade:"유물",level:3,finalDamagePer:1.1755, engBonus:0},
    {name:'에테르 포식자',grade:"유물",level:4,finalDamagePer:1.1827, engBonus:0},

    {name:'예리한 둔기',grade:"전설",level:0,finalDamagePer:1.13, engBonus:0},
    {name:'예리한 둔기',grade:"전설",level:1,finalDamagePer:1.1375, engBonus:0},
    {name:'예리한 둔기',grade:"전설",level:2,finalDamagePer:1.145, engBonus:0},
    {name:'예리한 둔기',grade:"전설",level:3,finalDamagePer:1.1525, engBonus:0},
    {name:'예리한 둔기',grade:"유물",level:0,finalDamagePer:1.16, engBonus:0},
    {name:'예리한 둔기',grade:"유물",level:1,finalDamagePer:1.1675, engBonus:0},
    {name:'예리한 둔기',grade:"유물",level:2,finalDamagePer:1.175, engBonus:0},
    {name:'예리한 둔기',grade:"유물",level:3,finalDamagePer:1.1825, engBonus:0},
    {name:'예리한 둔기',grade:"유물",level:4,finalDamagePer:1.19, engBonus:0},

    {name:'원한',grade:"전설",level:0,finalDamagePer:1.13, engBonus:0},
    {name:'원한',grade:"전설",level:1,finalDamagePer:1.1375, engBonus:0},
    {name:'원한',grade:"전설",level:2,finalDamagePer:1.145, engBonus:0},
    {name:'원한',grade:"전설",level:3,finalDamagePer:1.1525, engBonus:0},
    {name:'원한',grade:"유물",level:0,finalDamagePer:1.16, engBonus:0},
    {name:'원한',grade:"유물",level:1,finalDamagePer:1.1675, engBonus:0},
    {name:'원한',grade:"유물",level:2,finalDamagePer:1.175, engBonus:0},
    {name:'원한',grade:"유물",level:3,finalDamagePer:1.1825, engBonus:0},
    {name:'원한',grade:"유물",level:4,finalDamagePer:1.19, engBonus:0},

    {name:'저주받은 인형',grade:"전설",level:0,finalDamagePer:1.13, engBonus:0},
    {name:'저주받은 인형',grade:"전설",level:1,finalDamagePer:1.1375, engBonus:0},
    {name:'저주받은 인형',grade:"전설",level:2,finalDamagePer:1.145, engBonus:0},
    {name:'저주받은 인형',grade:"전설",level:3,finalDamagePer:1.1525, engBonus:0},
    {name:'저주받은 인형',grade:"유물",level:0,finalDamagePer:1.16, engBonus:0},
    {name:'저주받은 인형',grade:"유물",level:1,finalDamagePer:1.1675, engBonus:0},
    {name:'저주받은 인형',grade:"유물",level:2,finalDamagePer:1.175, engBonus:0},
    {name:'저주받은 인형',grade:"유물",level:3,finalDamagePer:1.1825, engBonus:0},
    {name:'저주받은 인형',grade:"유물",level:4,finalDamagePer:1.19, engBonus:0},

    {name:'정밀 단도',grade:"전설",level:0,finalDamagePer:1.13, engBonus:0},
    {name:'정밀 단도',grade:"전설",level:1,finalDamagePer:1.1375, engBonus:0},
    {name:'정밀 단도',grade:"전설",level:2,finalDamagePer:1.145, engBonus:0},
    {name:'정밀 단도',grade:"전설",level:3,finalDamagePer:1.1525, engBonus:0},
    {name:'정밀 단도',grade:"유물",level:0,finalDamagePer:1.16, engBonus:0},
    {name:'정밀 단도',grade:"유물",level:1,finalDamagePer:1.1675, engBonus:0},
    {name:'정밀 단도',grade:"유물",level:2,finalDamagePer:1.175, engBonus:0},
    {name:'정밀 단도',grade:"유물",level:3,finalDamagePer:1.1825, engBonus:0},
    {name:'정밀 단도',grade:"유물",level:4,finalDamagePer:1.19, engBonus:0},

    {name:'질량 증가',grade:"전설",level:0,finalDamagePer:1.13, engBonus:0},
    {name:'질량 증가',grade:"전설",level:1,finalDamagePer:1.1375, engBonus:0},
    {name:'질량 증가',grade:"전설",level:2,finalDamagePer:1.145, engBonus:0},
    {name:'질량 증가',grade:"전설",level:3,finalDamagePer:1.1525, engBonus:0},
    {name:'질량 증가',grade:"유물",level:0,finalDamagePer:1.16, engBonus:0},
    {name:'질량 증가',grade:"유물",level:1,finalDamagePer:1.1675, engBonus:0},
    {name:'질량 증가',grade:"유물",level:2,finalDamagePer:1.175, engBonus:0},
    {name:'질량 증가',grade:"유물",level:3,finalDamagePer:1.1825, engBonus:0},
    {name:'질량 증가',grade:"유물",level:4,finalDamagePer:1.19, engBonus:0},

    {name:'추진력',grade:"전설",level:0,finalDamagePer:1.13, engBonus:0},
    {name:'추진력',grade:"전설",level:1,finalDamagePer:1.1375, engBonus:0},
    {name:'추진력',grade:"전설",level:2,finalDamagePer:1.145, engBonus:0},
    {name:'추진력',grade:"전설",level:3,finalDamagePer:1.1525, engBonus:0},
    {name:'추진력',grade:"유물",level:0,finalDamagePer:1.16, engBonus:0},
    {name:'추진력',grade:"유물",level:1,finalDamagePer:1.1675, engBonus:0},
    {name:'추진력',grade:"유물",level:2,finalDamagePer:1.175, engBonus:0},
    {name:'추진력',grade:"유물",level:3,finalDamagePer:1.1825, engBonus:0},
    {name:'추진력',grade:"유물",level:4,finalDamagePer:1.19, engBonus:0}
]
