export let engFilter = [
    { name: '없음', grade: "", level: 0, finalDamagePer: 0, engBonus: 0 },

    { name: '결투의 대가', grade: "전설", level: 0, finalDamagePer: 1.13, engBonus: 0 },
    { name: '결투의 대가', grade: "전설", level: 1, finalDamagePer: 1.1375, engBonus: 0 },
    { name: '결투의 대가', grade: "전설", level: 2, finalDamagePer: 1.145, engBonus: 0 },
    { name: '결투의 대가', grade: "전설", level: 3, finalDamagePer: 1.1525, engBonus: 0 },
    { name: '결투의 대가', grade: "유물", level: 0, finalDamagePer: 1.16, engBonus: 0 },
    { name: '결투의 대가', grade: "유물", level: 1, finalDamagePer: 1.1675, engBonus: 0 },
    { name: '결투의 대가', grade: "유물", level: 2, finalDamagePer: 1.175, engBonus: 0 },
    { name: '결투의 대가', grade: "유물", level: 3, finalDamagePer: 1.1825, engBonus: 0 },
    { name: '결투의 대가', grade: "유물", level: 4, finalDamagePer: 1.19, engBonus: 0 },

    { name: '기습의 대가', grade: "전설", level: 0, finalDamagePer: 1.13, engBonus: 0 },
    { name: '기습의 대가', grade: "전설", level: 1, finalDamagePer: 1.1375, engBonus: 0 },
    { name: '기습의 대가', grade: "전설", level: 2, finalDamagePer: 1.145, engBonus: 0 },
    { name: '기습의 대가', grade: "전설", level: 3, finalDamagePer: 1.1525, engBonus: 0 },
    { name: '기습의 대가', grade: "유물", level: 0, finalDamagePer: 1.16, engBonus: 0 },
    { name: '기습의 대가', grade: "유물", level: 1, finalDamagePer: 1.1675, engBonus: 0 },
    { name: '기습의 대가', grade: "유물", level: 2, finalDamagePer: 1.175, engBonus: 0 },
    { name: '기습의 대가', grade: "유물", level: 3, finalDamagePer: 1.1825, engBonus: 0 },
    { name: '기습의 대가', grade: "유물", level: 4, finalDamagePer: 1.19, engBonus: 0 },

    { name: '달인의 저력', grade: "전설", level: 0, finalDamagePer: 1.13, engBonus: 0 },
    { name: '달인의 저력', grade: "전설", level: 1, finalDamagePer: 1.1375, engBonus: 0 },
    { name: '달인의 저력', grade: "전설", level: 2, finalDamagePer: 1.145, engBonus: 0 },
    { name: '달인의 저력', grade: "전설", level: 3, finalDamagePer: 1.1525, engBonus: 0 },
    { name: '달인의 저력', grade: "유물", level: 0, finalDamagePer: 1.16, engBonus: 0 },
    { name: '달인의 저력', grade: "유물", level: 1, finalDamagePer: 1.1675, engBonus: 0 },
    { name: '달인의 저력', grade: "유물", level: 2, finalDamagePer: 1.175, engBonus: 0 },
    { name: '달인의 저력', grade: "유물", level: 3, finalDamagePer: 1.1825, engBonus: 0 },
    { name: '달인의 저력', grade: "유물", level: 4, finalDamagePer: 1.19, engBonus: 0 },

    { name: '돌격대장', grade: "전설", level: 0, finalDamagePer: 1.13, engBonus: 0 },
    { name: '돌격대장', grade: "전설", level: 1, finalDamagePer: 1.1375, engBonus: 0 },
    { name: '돌격대장', grade: "전설", level: 2, finalDamagePer: 1.145, engBonus: 0 },
    { name: '돌격대장', grade: "전설", level: 3, finalDamagePer: 1.1525, engBonus: 0 },
    { name: '돌격대장', grade: "유물", level: 0, finalDamagePer: 1.16, engBonus: 0 },
    { name: '돌격대장', grade: "유물", level: 1, finalDamagePer: 1.1675, engBonus: 0 },
    { name: '돌격대장', grade: "유물", level: 2, finalDamagePer: 1.175, engBonus: 0 },
    { name: '돌격대장', grade: "유물", level: 3, finalDamagePer: 1.1825, engBonus: 0 },
    { name: '돌격대장', grade: "유물", level: 4, finalDamagePer: 1.19, engBonus: 0 },

    { name: '마나 효율 증가', grade: "전설", level: 0, finalDamagePer: 1.13, engBonus: 0 },
    { name: '마나 효율 증가', grade: "전설", level: 1, finalDamagePer: 1.1375, engBonus: 0 },
    { name: '마나 효율 증가', grade: "전설", level: 2, finalDamagePer: 1.145, engBonus: 0 },
    { name: '마나 효율 증가', grade: "전설", level: 3, finalDamagePer: 1.1525, engBonus: 0 },
    { name: '마나 효율 증가', grade: "유물", level: 0, finalDamagePer: 1.16, engBonus: 0 },
    { name: '마나 효율 증가', grade: "유물", level: 1, finalDamagePer: 1.1675, engBonus: 0 },
    { name: '마나 효율 증가', grade: "유물", level: 2, finalDamagePer: 1.175, engBonus: 0 },
    { name: '마나 효율 증가', grade: "유물", level: 3, finalDamagePer: 1.1825, engBonus: 0 },
    { name: '마나 효율 증가', grade: "유물", level: 4, finalDamagePer: 1.19, engBonus: 0 },

    { name: '바리케이드', grade: "전설", level: 0, finalDamagePer: 1.13, engBonus: 0 },
    { name: '바리케이드', grade: "전설", level: 1, finalDamagePer: 1.1375, engBonus: 0 },
    { name: '바리케이드', grade: "전설", level: 2, finalDamagePer: 1.145, engBonus: 0 },
    { name: '바리케이드', grade: "전설", level: 3, finalDamagePer: 1.1525, engBonus: 0 },
    { name: '바리케이드', grade: "유물", level: 0, finalDamagePer: 1.16, engBonus: 0 },
    { name: '바리케이드', grade: "유물", level: 1, finalDamagePer: 1.1675, engBonus: 0 },
    { name: '바리케이드', grade: "유물", level: 2, finalDamagePer: 1.175, engBonus: 0 },
    { name: '바리케이드', grade: "유물", level: 3, finalDamagePer: 1.1825, engBonus: 0 },
    { name: '바리케이드', grade: "유물", level: 4, finalDamagePer: 1.19, engBonus: 0 },

    { name: '속전속결', grade: "전설", level: 0, finalDamagePer: 1.13, engBonus: 0 },
    { name: '속전속결', grade: "전설", level: 1, finalDamagePer: 1.1375, engBonus: 0 },
    { name: '속전속결', grade: "전설", level: 2, finalDamagePer: 1.145, engBonus: 0 },
    { name: '속전속결', grade: "전설", level: 3, finalDamagePer: 1.1525, engBonus: 0 },
    { name: '속전속결', grade: "유물", level: 0, finalDamagePer: 1.16, engBonus: 0 },
    { name: '속전속결', grade: "유물", level: 1, finalDamagePer: 1.1675, engBonus: 0 },
    { name: '속전속결', grade: "유물", level: 2, finalDamagePer: 1.175, engBonus: 0 },
    { name: '속전속결', grade: "유물", level: 3, finalDamagePer: 1.1825, engBonus: 0 },
    { name: '속전속결', grade: "유물", level: 4, finalDamagePer: 1.19, engBonus: 0 },

    { name: '슈퍼 차지', grade: "전설", level: 0, finalDamagePer: 1.13, engBonus: 0 },
    { name: '슈퍼 차지', grade: "전설", level: 1, finalDamagePer: 1.1375, engBonus: 0 },
    { name: '슈퍼 차지', grade: "전설", level: 2, finalDamagePer: 1.145, engBonus: 0 },
    { name: '슈퍼 차지', grade: "전설", level: 3, finalDamagePer: 1.1525, engBonus: 0 },
    { name: '슈퍼 차지', grade: "유물", level: 0, finalDamagePer: 1.16, engBonus: 0 },
    { name: '슈퍼 차지', grade: "유물", level: 1, finalDamagePer: 1.1675, engBonus: 0 },
    { name: '슈퍼 차지', grade: "유물", level: 2, finalDamagePer: 1.175, engBonus: 0 },
    { name: '슈퍼 차지', grade: "유물", level: 3, finalDamagePer: 1.1825, engBonus: 0 },
    { name: '슈퍼 차지', grade: "유물", level: 4, finalDamagePer: 1.19, engBonus: 0 },

    { name: '아드레날린', grade: "전설", level: 0, finalDamagePer: 1.13, engBonus: 0 },
    { name: '아드레날린', grade: "전설", level: 1, finalDamagePer: 1.1375, engBonus: 0 },
    { name: '아드레날린', grade: "전설", level: 2, finalDamagePer: 1.145, engBonus: 0 },
    { name: '아드레날린', grade: "전설", level: 3, finalDamagePer: 1.1525, engBonus: 0 },
    { name: '아드레날린', grade: "유물", level: 0, finalDamagePer: 1.16, engBonus: 0 },
    { name: '아드레날린', grade: "유물", level: 1, finalDamagePer: 1.1675, engBonus: 0 },
    { name: '아드레날린', grade: "유물", level: 2, finalDamagePer: 1.175, engBonus: 0 },
    { name: '아드레날린', grade: "유물", level: 3, finalDamagePer: 1.1825, engBonus: 0 },
    { name: '아드레날린', grade: "유물", level: 4, finalDamagePer: 1.19, engBonus: 0 },

    { name: '안정된 상태', grade: "전설", level: 0, finalDamagePer: 1.13, engBonus: 0 },
    { name: '안정된 상태', grade: "전설", level: 1, finalDamagePer: 1.1375, engBonus: 0 },
    { name: '안정된 상태', grade: "전설", level: 2, finalDamagePer: 1.145, engBonus: 0 },
    { name: '안정된 상태', grade: "전설", level: 3, finalDamagePer: 1.1525, engBonus: 0 },
    { name: '안정된 상태', grade: "유물", level: 0, finalDamagePer: 1.16, engBonus: 0 },
    { name: '안정된 상태', grade: "유물", level: 1, finalDamagePer: 1.1675, engBonus: 0 },
    { name: '안정된 상태', grade: "유물", level: 2, finalDamagePer: 1.175, engBonus: 0 },
    { name: '안정된 상태', grade: "유물", level: 3, finalDamagePer: 1.1825, engBonus: 0 },
    { name: '안정된 상태', grade: "유물", level: 4, finalDamagePer: 1.19, engBonus: 0 },

    { name: '에테르 포식자', grade: "전설", level: 0, finalDamagePer: 1.1131, engBonus: 0 },
    { name: '에테르 포식자', grade: "전설", level: 1, finalDamagePer: 1.1225, engBonus: 0 },
    { name: '에테르 포식자', grade: "전설", level: 2, finalDamagePer: 1.1323, engBonus: 0 },
    { name: '에테르 포식자', grade: "전설", level: 3, finalDamagePer: 1.1423, engBonus: 0 },
    { name: '에테르 포식자', grade: "유물", level: 0, finalDamagePer: 1.1538, engBonus: 0 },
    { name: '에테르 포식자', grade: "유물", level: 1, finalDamagePer: 1.1611, engBonus: 0 },
    { name: '에테르 포식자', grade: "유물", level: 2, finalDamagePer: 1.1682, engBonus: 0 },
    { name: '에테르 포식자', grade: "유물", level: 3, finalDamagePer: 1.1755, engBonus: 0 },
    { name: '에테르 포식자', grade: "유물", level: 4, finalDamagePer: 1.1827, engBonus: 0 },

    { name: '예리한 둔기', grade: "전설", level: 0, finalDamagePer: 1.13, engBonus: 0 },
    { name: '예리한 둔기', grade: "전설", level: 1, finalDamagePer: 1.1375, engBonus: 0 },
    { name: '예리한 둔기', grade: "전설", level: 2, finalDamagePer: 1.145, engBonus: 0 },
    { name: '예리한 둔기', grade: "전설", level: 3, finalDamagePer: 1.1525, engBonus: 0 },
    { name: '예리한 둔기', grade: "유물", level: 0, finalDamagePer: 1.16, engBonus: 0 },
    { name: '예리한 둔기', grade: "유물", level: 1, finalDamagePer: 1.1675, engBonus: 0 },
    { name: '예리한 둔기', grade: "유물", level: 2, finalDamagePer: 1.175, engBonus: 0 },
    { name: '예리한 둔기', grade: "유물", level: 3, finalDamagePer: 1.1825, engBonus: 0 },
    { name: '예리한 둔기', grade: "유물", level: 4, finalDamagePer: 1.19, engBonus: 0 },

    { name: '원한', grade: "전설", level: 0, finalDamagePer: 1.13, engBonus: 0 },
    { name: '원한', grade: "전설", level: 1, finalDamagePer: 1.1375, engBonus: 0 },
    { name: '원한', grade: "전설", level: 2, finalDamagePer: 1.145, engBonus: 0 },
    { name: '원한', grade: "전설", level: 3, finalDamagePer: 1.1525, engBonus: 0 },
    { name: '원한', grade: "유물", level: 0, finalDamagePer: 1.16, engBonus: 0 },
    { name: '원한', grade: "유물", level: 1, finalDamagePer: 1.1675, engBonus: 0 },
    { name: '원한', grade: "유물", level: 2, finalDamagePer: 1.175, engBonus: 0 },
    { name: '원한', grade: "유물", level: 3, finalDamagePer: 1.1825, engBonus: 0 },
    { name: '원한', grade: "유물", level: 4, finalDamagePer: 1.19, engBonus: 0 },

    { name: '저주받은 인형', grade: "전설", level: 0, finalDamagePer: 1.13, engBonus: 0 },
    { name: '저주받은 인형', grade: "전설", level: 1, finalDamagePer: 1.1375, engBonus: 0 },
    { name: '저주받은 인형', grade: "전설", level: 2, finalDamagePer: 1.145, engBonus: 0 },
    { name: '저주받은 인형', grade: "전설", level: 3, finalDamagePer: 1.1525, engBonus: 0 },
    { name: '저주받은 인형', grade: "유물", level: 0, finalDamagePer: 1.16, engBonus: 0 },
    { name: '저주받은 인형', grade: "유물", level: 1, finalDamagePer: 1.1675, engBonus: 0 },
    { name: '저주받은 인형', grade: "유물", level: 2, finalDamagePer: 1.175, engBonus: 0 },
    { name: '저주받은 인형', grade: "유물", level: 3, finalDamagePer: 1.1825, engBonus: 0 },
    { name: '저주받은 인형', grade: "유물", level: 4, finalDamagePer: 1.19, engBonus: 0 },

    { name: '정밀 단도', grade: "전설", level: 0, finalDamagePer: 1.13, engBonus: 0 },
    { name: '정밀 단도', grade: "전설", level: 1, finalDamagePer: 1.1375, engBonus: 0 },
    { name: '정밀 단도', grade: "전설", level: 2, finalDamagePer: 1.145, engBonus: 0 },
    { name: '정밀 단도', grade: "전설", level: 3, finalDamagePer: 1.1525, engBonus: 0 },
    { name: '정밀 단도', grade: "유물", level: 0, finalDamagePer: 1.16, engBonus: 0 },
    { name: '정밀 단도', grade: "유물", level: 1, finalDamagePer: 1.1675, engBonus: 0 },
    { name: '정밀 단도', grade: "유물", level: 2, finalDamagePer: 1.175, engBonus: 0 },
    { name: '정밀 단도', grade: "유물", level: 3, finalDamagePer: 1.1825, engBonus: 0 },
    { name: '정밀 단도', grade: "유물", level: 4, finalDamagePer: 1.19, engBonus: 0 },

    { name: '질량 증가', grade: "전설", level: 0, finalDamagePer: 1.13, engBonus: 0 },
    { name: '질량 증가', grade: "전설", level: 1, finalDamagePer: 1.1375, engBonus: 0 },
    { name: '질량 증가', grade: "전설", level: 2, finalDamagePer: 1.145, engBonus: 0 },
    { name: '질량 증가', grade: "전설", level: 3, finalDamagePer: 1.1525, engBonus: 0 },
    { name: '질량 증가', grade: "유물", level: 0, finalDamagePer: 1.16, engBonus: 0 },
    { name: '질량 증가', grade: "유물", level: 1, finalDamagePer: 1.1675, engBonus: 0 },
    { name: '질량 증가', grade: "유물", level: 2, finalDamagePer: 1.175, engBonus: 0 },
    { name: '질량 증가', grade: "유물", level: 3, finalDamagePer: 1.1825, engBonus: 0 },
    { name: '질량 증가', grade: "유물", level: 4, finalDamagePer: 1.19, engBonus: 0 },

    { name: '추진력', grade: "전설", level: 0, finalDamagePer: 1.13, engBonus: 0 },
    { name: '추진력', grade: "전설", level: 1, finalDamagePer: 1.1375, engBonus: 0 },
    { name: '추진력', grade: "전설", level: 2, finalDamagePer: 1.145, engBonus: 0 },
    { name: '추진력', grade: "전설", level: 3, finalDamagePer: 1.1525, engBonus: 0 },
    { name: '추진력', grade: "유물", level: 0, finalDamagePer: 1.16, engBonus: 0 },
    { name: '추진력', grade: "유물", level: 1, finalDamagePer: 1.1675, engBonus: 0 },
    { name: '추진력', grade: "유물", level: 2, finalDamagePer: 1.175, engBonus: 0 },
    { name: '추진력', grade: "유물", level: 3, finalDamagePer: 1.1825, engBonus: 0 },
    { name: '추진력', grade: "유물", level: 4, finalDamagePer: 1.19, engBonus: 0 },

    { name: '타격의 대가', grade: "전설", level: 0, finalDamagePer: 1.13, engBonus: 0 },
    { name: '타격의 대가', grade: "전설", level: 1, finalDamagePer: 1.1375, engBonus: 0 },
    { name: '타격의 대가', grade: "전설", level: 2, finalDamagePer: 1.145, engBonus: 0 },
    { name: '타격의 대가', grade: "전설", level: 3, finalDamagePer: 1.1525, engBonus: 0 },
    { name: '타격의 대가', grade: "유물", level: 0, finalDamagePer: 1.16, engBonus: 0 },
    { name: '타격의 대가', grade: "유물", level: 1, finalDamagePer: 1.1675, engBonus: 0 },
    { name: '타격의 대가', grade: "유물", level: 2, finalDamagePer: 1.175, engBonus: 0 },
    { name: '타격의 대가', grade: "유물", level: 3, finalDamagePer: 1.1825, engBonus: 0 },
    { name: '타격의 대가', grade: "유물", level: 4, finalDamagePer: 1.19, engBonus: 0 }
]





/* **********************************************************************************************************************
 * function name		:	elixirOptionData
 * description			: 	각 앨릭서 부위및 공용 옵션의 값 각 옵션의 속성명{atkPlus, weaponAtkPlus, stats, finalDamagePer, atkPer, atkBuff}
 *********************************************************************************************************************** */
export const elixirOptionData = {
    common: [
        { name: "힘/민첩/지능 Lv.1", stats: 0 },
        { name: "힘/민첩/지능 Lv.2", stats: 0 },
        { name: "힘/민첩/지능 Lv.3", stats: 0 },
        { name: "힘/민첩/지능 Lv.4", stats: 0 },
        { name: "힘/민첩/지능 Lv.5", stats: 0 },
        { name: "공격력 Lv.1", atkPlus: 0 },
        { name: "공격력 Lv.2", atkPlus: 0 },
        { name: "공격력 Lv.3", atkPlus: 0 },
        { name: "공격력 Lv.4", atkPlus: 0 },
        { name: "공격력 Lv.5", atkPlus: 0 },
        { name: "무기 공격력 Lv.1", weaponAtkPlus: 0 },
        { name: "무기 공격력 Lv.2", weaponAtkPlus: 0 },
        { name: "무기 공격력 Lv.3", weaponAtkPlus: 0 },
        { name: "무기 공격력 Lv.4", weaponAtkPlus: 0 },
        { name: "무기 공격력 Lv.5", weaponAtkPlus: 0 },
        { name: "탈출의 달인 Lv.1", value: 0 },
        { name: "탈출의 달인 Lv.2", value: 0 },
        { name: "탈출의 달인 Lv.3", value: 0 },
        { name: "탈출의 달인 Lv.4", value: 0 },
        { name: "탈출의 달인 Lv.5", value: 0 },
        { name: "회피의 달인 Lv.1", value: 0 },
        { name: "회피의 달인 Lv.2", value: 0 },
        { name: "회피의 달인 Lv.3", value: 0 },
        { name: "회피의 달인 Lv.4", value: 0 },
        { name: "회피의 달인 Lv.5", value: 0 },
        { name: "마나 Lv.1", value: 0 },
        { name: "마나 Lv.2", value: 0 },
        { name: "마나 Lv.3", value: 0 },
        { name: "마나 Lv.4", value: 0 },
        { name: "마나 Lv.5", value: 0 },
        { name: "생명의 축복 Lv.1", value: 0 },
        { name: "생명의 축복 Lv.2", value: 0 },
        { name: "생명의 축복 Lv.3", value: 0 },
        { name: "생명의 축복 Lv.4", value: 0 },
        { name: "생명의 축복 Lv.5", value: 0 },
        { name: "자원의 축복 Lv.1", value: 0 },
        { name: "자원의 축복 Lv.2", value: 0 },
        { name: "자원의 축복 Lv.3", value: 0 },
        { name: "자원의 축복 Lv.4", value: 0 },
        { name: "자원의 축복 Lv.5", value: 0 },
        { name: "방랑자 Lv.1", value: 0 },
        { name: "방랑자 Lv.2", value: 0 },
        { name: "방랑자 Lv.3", value: 0 },
        { name: "방랑자 Lv.4", value: 0 },
        { name: "방랑자 Lv.5", value: 0 },
        { name: "무력화 Lv.1", value: 0 },
        { name: "무력화 Lv.2", value: 0 },
        { name: "무력화 Lv.3", value: 0 },
        { name: "무력화 Lv.4", value: 0 },
        { name: "무력화 Lv.5", value: 0 },
        { name: "물약 중독 Lv.1", value: 0 },
        { name: "물약 중독 Lv.2", value: 0 },
        { name: "물약 중독 Lv.3", value: 0 },
        { name: "물약 중독 Lv.4", value: 0 },
        { name: "물약 중독 Lv.5", value: 0 },
        { name: "폭발물 달인 Lv.1", value: 0 },
        { name: "폭발물 달인 Lv.2", value: 0 },
        { name: "폭발물 달인 Lv.3", value: 0 },
        { name: "폭발물 달인 Lv.4", value: 0 },
        { name: "폭발물 달인 Lv.5", value: 0 },
    ],
    helmet: [
        { name: "투구 힘/민첩/지능 Lv.1", stats: 0 },
        { name: "투구 힘/민첩/지능 Lv.2", stats: 0 },
        { name: "투구 힘/민첩/지능 Lv.3", stats: 0 },
    ]
    ,
    shoulder: [
        { name: "어깨 힘/민첩/지능 Lv.1", stats: 0 },
        { name: "어깨 힘/민첩/지능 Lv.2", stats: 0 },
        { name: "어깨 힘/민첩/지능 Lv.3", stats: 0 },
    ]
    ,
    armor: [
        { name: "갑옷 힘/민첩/지능 Lv.1", stats: 0 },
        { name: "갑옷 힘/민첩/지능 Lv.2", stats: 0 },
        { name: "갑옷 힘/민첩/지능 Lv.3", stats: 0 },
    ]
    ,
    pants: [
        { name: "하의 힘/민첩/지능 Lv.1", stats: 0 },
        { name: "하의 힘/민첩/지능 Lv.2", stats: 0 },
        { name: "하의 힘/민첩/지능 Lv.3", stats: 0 },
    ]
    ,
    glove: [
        { name: "장갑 힘/민첩/지능 Lv.1", stats: 0 },
        { name: "장갑 힘/민첩/지능 Lv.2", stats: 0 },
        { name: "장갑 힘/민첩/지능 Lv.3", stats: 0 },
    ]

}
