export let engFilter = [
    { name: '없음', grade: "", level: 0, finalDamagePer: 0, engBonus: 0 },

    { name: '결투의 대가', grade: "전설", level: 0, finalDamagePer: 1.13, engBonus: 0 },
    { name: '결투의 대가', grade: "전설", level: 1, finalDamagePer: 1.1375, engBonus: 0 },
    { name: '결투의 대가', grade: "전설", level: 2, finalDamagePer: 1.145, engBonus: 0 },
    { name: '결투의 대가', grade: "전설", level: 3, finalDamagePer: 1.1525, engBonus: 0 },
    { name: '결투의 대가', grade: "유물", level: 0, finalDamagePer: 1.16, engBonus: 0 },
    { name: '결투의 대가', grade: "유물", level: 1, finalDamagePer: 1.1675, engBonus: 0 },
    { name: '결투의 대가', grade: "유물", level: 2, finalDamagePer: 1.175, engBonus: 0 },
    { name: '결투의 대가', grade: "유물", level: 3, finalDamagePer: 1.1825, engBonus: 0 },
    { name: '결투의 대가', grade: "유물", level: 4, finalDamagePer: 1.19, engBonus: 0 },

    { name: '기습의 대가', grade: "전설", level: 0, finalDamagePer: 1.13, engBonus: 0 },
    { name: '기습의 대가', grade: "전설", level: 1, finalDamagePer: 1.1375, engBonus: 0 },
    { name: '기습의 대가', grade: "전설", level: 2, finalDamagePer: 1.145, engBonus: 0 },
    { name: '기습의 대가', grade: "전설", level: 3, finalDamagePer: 1.1525, engBonus: 0 },
    { name: '기습의 대가', grade: "유물", level: 0, finalDamagePer: 1.16, engBonus: 0 },
    { name: '기습의 대가', grade: "유물", level: 1, finalDamagePer: 1.1675, engBonus: 0 },
    { name: '기습의 대가', grade: "유물", level: 2, finalDamagePer: 1.175, engBonus: 0 },
    { name: '기습의 대가', grade: "유물", level: 3, finalDamagePer: 1.1825, engBonus: 0 },
    { name: '기습의 대가', grade: "유물", level: 4, finalDamagePer: 1.19, engBonus: 0 },

    { name: '달인의 저력', grade: "전설", level: 0, finalDamagePer: 1.13, engBonus: 0 },
    { name: '달인의 저력', grade: "전설", level: 1, finalDamagePer: 1.1375, engBonus: 0 },
    { name: '달인의 저력', grade: "전설", level: 2, finalDamagePer: 1.145, engBonus: 0 },
    { name: '달인의 저력', grade: "전설", level: 3, finalDamagePer: 1.1525, engBonus: 0 },
    { name: '달인의 저력', grade: "유물", level: 0, finalDamagePer: 1.16, engBonus: 0 },
    { name: '달인의 저력', grade: "유물", level: 1, finalDamagePer: 1.1675, engBonus: 0 },
    { name: '달인의 저력', grade: "유물", level: 2, finalDamagePer: 1.175, engBonus: 0 },
    { name: '달인의 저력', grade: "유물", level: 3, finalDamagePer: 1.1825, engBonus: 0 },
    { name: '달인의 저력', grade: "유물", level: 4, finalDamagePer: 1.19, engBonus: 0 },

    { name: '돌격대장', grade: "전설", level: 0, finalDamagePer: 1.13, engBonus: 0 },
    { name: '돌격대장', grade: "전설", level: 1, finalDamagePer: 1.1375, engBonus: 0 },
    { name: '돌격대장', grade: "전설", level: 2, finalDamagePer: 1.145, engBonus: 0 },
    { name: '돌격대장', grade: "전설", level: 3, finalDamagePer: 1.1525, engBonus: 0 },
    { name: '돌격대장', grade: "유물", level: 0, finalDamagePer: 1.16, engBonus: 0 },
    { name: '돌격대장', grade: "유물", level: 1, finalDamagePer: 1.1675, engBonus: 0 },
    { name: '돌격대장', grade: "유물", level: 2, finalDamagePer: 1.175, engBonus: 0 },
    { name: '돌격대장', grade: "유물", level: 3, finalDamagePer: 1.1825, engBonus: 0 },
    { name: '돌격대장', grade: "유물", level: 4, finalDamagePer: 1.19, engBonus: 0 },

    { name: '마나 효율 증가', grade: "전설", level: 0, finalDamagePer: 1.13, engBonus: 0 },
    { name: '마나 효율 증가', grade: "전설", level: 1, finalDamagePer: 1.1375, engBonus: 0 },
    { name: '마나 효율 증가', grade: "전설", level: 2, finalDamagePer: 1.145, engBonus: 0 },
    { name: '마나 효율 증가', grade: "전설", level: 3, finalDamagePer: 1.1525, engBonus: 0 },
    { name: '마나 효율 증가', grade: "유물", level: 0, finalDamagePer: 1.16, engBonus: 0 },
    { name: '마나 효율 증가', grade: "유물", level: 1, finalDamagePer: 1.1675, engBonus: 0 },
    { name: '마나 효율 증가', grade: "유물", level: 2, finalDamagePer: 1.175, engBonus: 0 },
    { name: '마나 효율 증가', grade: "유물", level: 3, finalDamagePer: 1.1825, engBonus: 0 },
    { name: '마나 효율 증가', grade: "유물", level: 4, finalDamagePer: 1.19, engBonus: 0 },

    { name: '바리케이드', grade: "전설", level: 0, finalDamagePer: 1.13, engBonus: 0 },
    { name: '바리케이드', grade: "전설", level: 1, finalDamagePer: 1.1375, engBonus: 0 },
    { name: '바리케이드', grade: "전설", level: 2, finalDamagePer: 1.145, engBonus: 0 },
    { name: '바리케이드', grade: "전설", level: 3, finalDamagePer: 1.1525, engBonus: 0 },
    { name: '바리케이드', grade: "유물", level: 0, finalDamagePer: 1.16, engBonus: 0 },
    { name: '바리케이드', grade: "유물", level: 1, finalDamagePer: 1.1675, engBonus: 0 },
    { name: '바리케이드', grade: "유물", level: 2, finalDamagePer: 1.175, engBonus: 0 },
    { name: '바리케이드', grade: "유물", level: 3, finalDamagePer: 1.1825, engBonus: 0 },
    { name: '바리케이드', grade: "유물", level: 4, finalDamagePer: 1.19, engBonus: 0 },

    { name: '속전속결', grade: "전설", level: 0, finalDamagePer: 1.13, engBonus: 0 },
    { name: '속전속결', grade: "전설", level: 1, finalDamagePer: 1.1375, engBonus: 0 },
    { name: '속전속결', grade: "전설", level: 2, finalDamagePer: 1.145, engBonus: 0 },
    { name: '속전속결', grade: "전설", level: 3, finalDamagePer: 1.1525, engBonus: 0 },
    { name: '속전속결', grade: "유물", level: 0, finalDamagePer: 1.16, engBonus: 0 },
    { name: '속전속결', grade: "유물", level: 1, finalDamagePer: 1.1675, engBonus: 0 },
    { name: '속전속결', grade: "유물", level: 2, finalDamagePer: 1.175, engBonus: 0 },
    { name: '속전속결', grade: "유물", level: 3, finalDamagePer: 1.1825, engBonus: 0 },
    { name: '속전속결', grade: "유물", level: 4, finalDamagePer: 1.19, engBonus: 0 },

    { name: '슈퍼 차지', grade: "전설", level: 0, finalDamagePer: 1.13, engBonus: 0 },
    { name: '슈퍼 차지', grade: "전설", level: 1, finalDamagePer: 1.1375, engBonus: 0 },
    { name: '슈퍼 차지', grade: "전설", level: 2, finalDamagePer: 1.145, engBonus: 0 },
    { name: '슈퍼 차지', grade: "전설", level: 3, finalDamagePer: 1.1525, engBonus: 0 },
    { name: '슈퍼 차지', grade: "유물", level: 0, finalDamagePer: 1.16, engBonus: 0 },
    { name: '슈퍼 차지', grade: "유물", level: 1, finalDamagePer: 1.1675, engBonus: 0 },
    { name: '슈퍼 차지', grade: "유물", level: 2, finalDamagePer: 1.175, engBonus: 0 },
    { name: '슈퍼 차지', grade: "유물", level: 3, finalDamagePer: 1.1825, engBonus: 0 },
    { name: '슈퍼 차지', grade: "유물", level: 4, finalDamagePer: 1.19, engBonus: 0 },

    { name: '아드레날린', grade: "전설", level: 0, finalDamagePer: 1.13, engBonus: 0 },
    { name: '아드레날린', grade: "전설", level: 1, finalDamagePer: 1.1375, engBonus: 0 },
    { name: '아드레날린', grade: "전설", level: 2, finalDamagePer: 1.145, engBonus: 0 },
    { name: '아드레날린', grade: "전설", level: 3, finalDamagePer: 1.1525, engBonus: 0 },
    { name: '아드레날린', grade: "유물", level: 0, finalDamagePer: 1.16, engBonus: 0 },
    { name: '아드레날린', grade: "유물", level: 1, finalDamagePer: 1.1675, engBonus: 0 },
    { name: '아드레날린', grade: "유물", level: 2, finalDamagePer: 1.175, engBonus: 0 },
    { name: '아드레날린', grade: "유물", level: 3, finalDamagePer: 1.1825, engBonus: 0 },
    { name: '아드레날린', grade: "유물", level: 4, finalDamagePer: 1.19, engBonus: 0 },

    { name: '안정된 상태', grade: "전설", level: 0, finalDamagePer: 1.13, engBonus: 0 },
    { name: '안정된 상태', grade: "전설", level: 1, finalDamagePer: 1.1375, engBonus: 0 },
    { name: '안정된 상태', grade: "전설", level: 2, finalDamagePer: 1.145, engBonus: 0 },
    { name: '안정된 상태', grade: "전설", level: 3, finalDamagePer: 1.1525, engBonus: 0 },
    { name: '안정된 상태', grade: "유물", level: 0, finalDamagePer: 1.16, engBonus: 0 },
    { name: '안정된 상태', grade: "유물", level: 1, finalDamagePer: 1.1675, engBonus: 0 },
    { name: '안정된 상태', grade: "유물", level: 2, finalDamagePer: 1.175, engBonus: 0 },
    { name: '안정된 상태', grade: "유물", level: 3, finalDamagePer: 1.1825, engBonus: 0 },
    { name: '안정된 상태', grade: "유물", level: 4, finalDamagePer: 1.19, engBonus: 0 },

    { name: '에테르 포식자', grade: "전설", level: 0, finalDamagePer: 1.1131, engBonus: 0 },
    { name: '에테르 포식자', grade: "전설", level: 1, finalDamagePer: 1.1225, engBonus: 0 },
    { name: '에테르 포식자', grade: "전설", level: 2, finalDamagePer: 1.1323, engBonus: 0 },
    { name: '에테르 포식자', grade: "전설", level: 3, finalDamagePer: 1.1423, engBonus: 0 },
    { name: '에테르 포식자', grade: "유물", level: 0, finalDamagePer: 1.1538, engBonus: 0 },
    { name: '에테르 포식자', grade: "유물", level: 1, finalDamagePer: 1.1611, engBonus: 0 },
    { name: '에테르 포식자', grade: "유물", level: 2, finalDamagePer: 1.1682, engBonus: 0 },
    { name: '에테르 포식자', grade: "유물", level: 3, finalDamagePer: 1.1755, engBonus: 0 },
    { name: '에테르 포식자', grade: "유물", level: 4, finalDamagePer: 1.1827, engBonus: 0 },

    { name: '예리한 둔기', grade: "전설", level: 0, finalDamagePer: 1.13, engBonus: 0 },
    { name: '예리한 둔기', grade: "전설", level: 1, finalDamagePer: 1.1375, engBonus: 0 },
    { name: '예리한 둔기', grade: "전설", level: 2, finalDamagePer: 1.145, engBonus: 0 },
    { name: '예리한 둔기', grade: "전설", level: 3, finalDamagePer: 1.1525, engBonus: 0 },
    { name: '예리한 둔기', grade: "유물", level: 0, finalDamagePer: 1.16, engBonus: 0 },
    { name: '예리한 둔기', grade: "유물", level: 1, finalDamagePer: 1.1675, engBonus: 0 },
    { name: '예리한 둔기', grade: "유물", level: 2, finalDamagePer: 1.175, engBonus: 0 },
    { name: '예리한 둔기', grade: "유물", level: 3, finalDamagePer: 1.1825, engBonus: 0 },
    { name: '예리한 둔기', grade: "유물", level: 4, finalDamagePer: 1.19, engBonus: 0 },

    { name: '원한', grade: "전설", level: 0, finalDamagePer: 1.13, engBonus: 0 },
    { name: '원한', grade: "전설", level: 1, finalDamagePer: 1.1375, engBonus: 0 },
    { name: '원한', grade: "전설", level: 2, finalDamagePer: 1.145, engBonus: 0 },
    { name: '원한', grade: "전설", level: 3, finalDamagePer: 1.1525, engBonus: 0 },
    { name: '원한', grade: "유물", level: 0, finalDamagePer: 1.16, engBonus: 0 },
    { name: '원한', grade: "유물", level: 1, finalDamagePer: 1.1675, engBonus: 0 },
    { name: '원한', grade: "유물", level: 2, finalDamagePer: 1.175, engBonus: 0 },
    { name: '원한', grade: "유물", level: 3, finalDamagePer: 1.1825, engBonus: 0 },
    { name: '원한', grade: "유물", level: 4, finalDamagePer: 1.19, engBonus: 0 },

    { name: '저주받은 인형', grade: "전설", level: 0, finalDamagePer: 1.13, engBonus: 0 },
    { name: '저주받은 인형', grade: "전설", level: 1, finalDamagePer: 1.1375, engBonus: 0 },
    { name: '저주받은 인형', grade: "전설", level: 2, finalDamagePer: 1.145, engBonus: 0 },
    { name: '저주받은 인형', grade: "전설", level: 3, finalDamagePer: 1.1525, engBonus: 0 },
    { name: '저주받은 인형', grade: "유물", level: 0, finalDamagePer: 1.16, engBonus: 0 },
    { name: '저주받은 인형', grade: "유물", level: 1, finalDamagePer: 1.1675, engBonus: 0 },
    { name: '저주받은 인형', grade: "유물", level: 2, finalDamagePer: 1.175, engBonus: 0 },
    { name: '저주받은 인형', grade: "유물", level: 3, finalDamagePer: 1.1825, engBonus: 0 },
    { name: '저주받은 인형', grade: "유물", level: 4, finalDamagePer: 1.19, engBonus: 0 },

    { name: '정밀 단도', grade: "전설", level: 0, finalDamagePer: 1.13, engBonus: 0 },
    { name: '정밀 단도', grade: "전설", level: 1, finalDamagePer: 1.1375, engBonus: 0 },
    { name: '정밀 단도', grade: "전설", level: 2, finalDamagePer: 1.145, engBonus: 0 },
    { name: '정밀 단도', grade: "전설", level: 3, finalDamagePer: 1.1525, engBonus: 0 },
    { name: '정밀 단도', grade: "유물", level: 0, finalDamagePer: 1.16, engBonus: 0 },
    { name: '정밀 단도', grade: "유물", level: 1, finalDamagePer: 1.1675, engBonus: 0 },
    { name: '정밀 단도', grade: "유물", level: 2, finalDamagePer: 1.175, engBonus: 0 },
    { name: '정밀 단도', grade: "유물", level: 3, finalDamagePer: 1.1825, engBonus: 0 },
    { name: '정밀 단도', grade: "유물", level: 4, finalDamagePer: 1.19, engBonus: 0 },

    { name: '질량 증가', grade: "전설", level: 0, finalDamagePer: 1.13, engBonus: 0 },
    { name: '질량 증가', grade: "전설", level: 1, finalDamagePer: 1.1375, engBonus: 0 },
    { name: '질량 증가', grade: "전설", level: 2, finalDamagePer: 1.145, engBonus: 0 },
    { name: '질량 증가', grade: "전설", level: 3, finalDamagePer: 1.1525, engBonus: 0 },
    { name: '질량 증가', grade: "유물", level: 0, finalDamagePer: 1.16, engBonus: 0 },
    { name: '질량 증가', grade: "유물", level: 1, finalDamagePer: 1.1675, engBonus: 0 },
    { name: '질량 증가', grade: "유물", level: 2, finalDamagePer: 1.175, engBonus: 0 },
    { name: '질량 증가', grade: "유물", level: 3, finalDamagePer: 1.1825, engBonus: 0 },
    { name: '질량 증가', grade: "유물", level: 4, finalDamagePer: 1.19, engBonus: 0 },

    { name: '추진력', grade: "전설", level: 0, finalDamagePer: 1.13, engBonus: 0 },
    { name: '추진력', grade: "전설", level: 1, finalDamagePer: 1.1375, engBonus: 0 },
    { name: '추진력', grade: "전설", level: 2, finalDamagePer: 1.145, engBonus: 0 },
    { name: '추진력', grade: "전설", level: 3, finalDamagePer: 1.1525, engBonus: 0 },
    { name: '추진력', grade: "유물", level: 0, finalDamagePer: 1.16, engBonus: 0 },
    { name: '추진력', grade: "유물", level: 1, finalDamagePer: 1.1675, engBonus: 0 },
    { name: '추진력', grade: "유물", level: 2, finalDamagePer: 1.175, engBonus: 0 },
    { name: '추진력', grade: "유물", level: 3, finalDamagePer: 1.1825, engBonus: 0 },
    { name: '추진력', grade: "유물", level: 4, finalDamagePer: 1.19, engBonus: 0 },

    { name: '타격의 대가', grade: "전설", level: 0, finalDamagePer: 1.13, engBonus: 0 },
    { name: '타격의 대가', grade: "전설", level: 1, finalDamagePer: 1.1375, engBonus: 0 },
    { name: '타격의 대가', grade: "전설", level: 2, finalDamagePer: 1.145, engBonus: 0 },
    { name: '타격의 대가', grade: "전설", level: 3, finalDamagePer: 1.1525, engBonus: 0 },
    { name: '타격의 대가', grade: "유물", level: 0, finalDamagePer: 1.16, engBonus: 0 },
    { name: '타격의 대가', grade: "유물", level: 1, finalDamagePer: 1.1675, engBonus: 0 },
    { name: '타격의 대가', grade: "유물", level: 2, finalDamagePer: 1.175, engBonus: 0 },
    { name: '타격의 대가', grade: "유물", level: 3, finalDamagePer: 1.1825, engBonus: 0 },
    { name: '타격의 대가', grade: "유물", level: 4, finalDamagePer: 1.19, engBonus: 0 }
]





/* **********************************************************************************************************************
 * function name		:	elixirOptionData
 * description			: 	각 앨릭서 부위및 공용 옵션의 값 각 옵션의 속성명{atkPlus, weaponAtkPlus, stats, finalDamagePer, atkPer, atkBuff}
 *********************************************************************************************************************** */
export const elixirOptionData = {
    common: [
        { name: "힘/민첩/지능 Lv.1", stats: 864, level: 1 },
        { name: "힘/민첩/지능 Lv.2", stats: 1782, level: 2 },
        { name: "힘/민첩/지능 Lv.3", stats: 2700, level: 3 },
        { name: "힘/민첩/지능 Lv.4", stats: 4050, level: 4 },
        { name: "힘/민첩/지능 Lv.5", stats: 5400, level: 5 },
        { name: "공격력 Lv.1", atkPlus: 122, level: 1 },
        { name: "공격력 Lv.2", atkPlus: 253, level: 2 },
        { name: "공격력 Lv.3", atkPlus: 383, level: 3 },
        { name: "공격력 Lv.4", atkPlus: 575, level: 4 },
        { name: "공격력 Lv.5", atkPlus: 767, level: 5 },
        { name: "무기 공격력 Lv.1", weaponAtkPlus: 236, level: 1 },
        { name: "무기 공격력 Lv.2", weaponAtkPlus: 488, level: 2 },
        { name: "무기 공격력 Lv.3", weaponAtkPlus: 740, level: 3 },
        { name: "무기 공격력 Lv.4", weaponAtkPlus: 1110, level: 4 },
        { name: "무기 공격력 Lv.5", weaponAtkPlus: 1480, level: 5 },
        { name: "탈출의 달인 Lv.1", value: 0, level: 1 },
        { name: "탈출의 달인 Lv.2", value: 0, level: 2 },
        { name: "탈출의 달인 Lv.3", value: 0, level: 3 },
        { name: "탈출의 달인 Lv.4", value: 0, level: 4 },
        { name: "탈출의 달인 Lv.5", value: 0, level: 5 },
        { name: "회피의 달인 Lv.1", value: 0, level: 1 },
        { name: "회피의 달인 Lv.2", value: 0, level: 2 },
        { name: "회피의 달인 Lv.3", value: 0, level: 3 },
        { name: "회피의 달인 Lv.4", value: 0, level: 4 },
        { name: "회피의 달인 Lv.5", value: 0, level: 5 },
        { name: "마나 Lv.1", value: 0, level: 1 },
        { name: "마나 Lv.2", value: 0, level: 2 },
        { name: "마나 Lv.3", value: 0, level: 3 },
        { name: "마나 Lv.4", value: 0, level: 4 },
        { name: "마나 Lv.5", value: 0, level: 5 },
        { name: "생명의 축복 Lv.1", value: 0, level: 1 },
        { name: "생명의 축복 Lv.2", value: 0, level: 2 },
        { name: "생명의 축복 Lv.3", value: 0, level: 3 },
        { name: "생명의 축복 Lv.4", value: 0, level: 4 },
        { name: "생명의 축복 Lv.5", value: 0, level: 5 },
        { name: "자원의 축복 Lv.1", value: 0, level: 1 },
        { name: "자원의 축복 Lv.2", value: 0, level: 2 },
        { name: "자원의 축복 Lv.3", value: 0, level: 3 },
        { name: "자원의 축복 Lv.4", value: 0, level: 4 },
        { name: "자원의 축복 Lv.5", value: 0, level: 5 },
        { name: "방랑자 Lv.1", value: 0, level: 1 },
        { name: "방랑자 Lv.2", value: 0, level: 2 },
        { name: "방랑자 Lv.3", value: 0, level: 3 },
        { name: "방랑자 Lv.4", value: 0, level: 4 },
        { name: "방랑자 Lv.5", value: 0, level: 5 },
        { name: "무력화 Lv.1", value: 0, level: 1 },
        { name: "무력화 Lv.2", value: 0, level: 2 },
        { name: "무력화 Lv.3", value: 0, level: 3 },
        { name: "무력화 Lv.4", value: 0, level: 4 },
        { name: "무력화 Lv.5", value: 0, level: 5 },
        { name: "물약 중독 Lv.1", value: 0, level: 1 },
        { name: "물약 중독 Lv.2", value: 0, level: 2 },
        { name: "물약 중독 Lv.3", value: 0, level: 3 },
        { name: "물약 중독 Lv.4", value: 0, level: 4 },
        { name: "물약 중독 Lv.5", value: 0, level: 5 },
        { name: "폭발물 달인 Lv.1", value: 0, level: 1 },
        { name: "폭발물 달인 Lv.2", value: 0, level: 2 },
        { name: "폭발물 달인 Lv.3", value: 0, level: 3 },
        { name: "폭발물 달인 Lv.4", value: 0, level: 4 },
        { name: "폭발물 달인 Lv.5", value: 0, level: 5 },
    ],
    helmet: [
        { name: "회심 Lv.1", atkPer: 0.23, level: 1 },
        { name: "회심 Lv.2", atkPer: 0.47, level: 2 },
        { name: "회심 Lv.3", atkPer: 0.72, level: 3 },
        { name: "회심 Lv.4", atkPer: 1.08, level: 4 },
        { name: "회심 Lv.5", atkPer: 1.44, level: 5 },
        { name: "달인 Lv.1", atkPer: 0.23, level: 1 },
        { name: "달인 Lv.2", atkPer: 0.47, level: 2 },
        { name: "달인 Lv.3", atkPer: 0.72, level: 3 },
        { name: "달인 Lv.4", atkPer: 1.08, level: 4 },
        { name: "달인 Lv.5", atkPer: 1.44, level: 5 },
        { name: "선봉대 Lv.1", atkPer: 0.23, level: 1 },
        { name: "선봉대 Lv.2", atkPer: 0.47, level: 2 },
        { name: "선봉대 Lv.3", atkPer: 0.72, level: 3 },
        { name: "선봉대 Lv.4", atkPer: 1.08, level: 4 },
        { name: "선봉대 Lv.5", atkPer: 1.44, level: 5 },
        { name: "강맹 Lv.1", atkPer: 0.23, level: 1 },
        { name: "강맹 Lv.2", atkPer: 0.47, level: 2 },
        { name: "강맹 Lv.3", atkPer: 0.72, level: 3 },
        { name: "강맹 Lv.4", atkPer: 1.08, level: 4 },
        { name: "강맹 Lv.5", atkPer: 1.44, level: 5 },
        { name: "칼날 방패 Lv.1", atkPer: 0.23, level: 1 },
        { name: "칼날 방패 Lv.2", atkPer: 0.47, level: 2 },
        { name: "칼날 방패 Lv.3", atkPer: 0.72, level: 3 },
        { name: "칼날 방패 Lv.4", atkPer: 1.08, level: 4 },
        { name: "칼날 방패 Lv.5", atkPer: 1.44, level: 5 },
        { name: "행운 Lv.1", atkPer: 0.23, level: 1 },
        { name: "행운 Lv.2", atkPer: 0.47, level: 2 },
        { name: "행운 Lv.3", atkPer: 0.72, level: 3 },
        { name: "행운 Lv.4", atkPer: 1.08, level: 4 },
        { name: "행운 Lv.5", atkPer: 1.44, level: 5 },
        { name: "신념 Lv.1", atkBuff: 0.64, level: 1 },
        { name: "신념 Lv.2", atkBuff: 1.32, level: 2 },
        { name: "신념 Lv.3", atkBuff: 2, level: 3 },
        { name: "신념 Lv.4", atkBuff: 3, level: 4 },
        { name: "신념 Lv.5", atkBuff: 4, level: 5 },
        { name: "진군 Lv.1", atkBuff: 0.64, level: 1 },
        { name: "진군 Lv.2", atkBuff: 1.32, level: 2 },
        { name: "진군 Lv.3", atkBuff: 2, level: 3 },
        { name: "진군 Lv.4", atkBuff: 3, level: 4 },
        { name: "진군 Lv.5", atkBuff: 4, level: 5 },
        { name: "선각자 Lv.1", atkBuff: 0.64, level: 1 },
        { name: "선각자 Lv.2", atkBuff: 1.32, level: 2 },
        { name: "선각자 Lv.3", atkBuff: 2, level: 3 },
        { name: "선각자 Lv.4", atkBuff: 3, level: 4 },
        { name: "선각자 Lv.5", atkBuff: 4, level: 5 }
    ]
    ,
    shoulder: [
        { name: "보스 피해 Lv.1", finalDamagePer: 1.0038, level: 1 },
        { name: "보스 피해 Lv.2", finalDamagePer: 1.0079, level: 2 },
        { name: "보스 피해 Lv.3", finalDamagePer: 1.012, level: 3 },
        { name: "보스 피해 Lv.4", finalDamagePer: 1.018, level: 4 },
        { name: "보스 피해 Lv.5", finalDamagePer: 1.024, level: 5 },
        { name: "각성기 피해 Lv.1", value: 0, level: 1 },
        { name: "각성기 피해 Lv.2", value: 0, level: 2 },
        { name: "각성기 피해 Lv.3", value: 0, level: 3 },
        { name: "각성기 피해 Lv.4", value: 0, level: 4 },
        { name: "각성기 피해 Lv.5", value: 0, level: 5 },
        { name: "보호막 강화 Lv.1", value: 0, level: 1 },
        { name: "보호막 강화 Lv.2", value: 0, level: 2 },
        { name: "보호막 강화 Lv.3", value: 0, level: 3 },
        { name: "보호막 강화 Lv.4", value: 0, level: 4 },
        { name: "보호막 강화 Lv.5", value: 0, level: 5 },
        { name: "회복 강화 Lv.1", value: 0, level: 1 },
        { name: "회복 강화 Lv.2", value: 0, level: 2 },
        { name: "회복 강화 Lv.3", value: 0, level: 3 },
        { name: "회복 강화 Lv.4", value: 0, level: 4 },
        { name: "회복 강화 Lv.5", value: 0, level: 5 }
    ]
    ,
    armor: [
        { name: "받는 피해 감소 Lv.1", atkPlus: 122, level: 1 },
        { name: "받는 피해 감소 Lv.2", atkPlus: 253, level: 2 },
        { name: "받는 피해 감소 Lv.3", atkPlus: 383, level: 3 },
        { name: "받는 피해 감소 Lv.4", atkPlus: 575, level: 4 },
        { name: "받는 피해 감소 Lv.5", atkPlus: 767, level: 5 },
        { name: "마법 방어력 Lv.1", value: 0, level: 1 },
        { name: "마법 방어력 Lv.2", value: 0, level: 2 },
        { name: "마법 방어력 Lv.3", value: 0, level: 3 },
        { name: "마법 방어력 Lv.4", value: 0, level: 4 },
        { name: "마법 방어력 Lv.5", value: 0, level: 5 },
        { name: "물리 방어력 Lv.1", value: 0, level: 1 },
        { name: "물리 방어력 Lv.2", value: 0, level: 2 },
        { name: "물리 방어력 Lv.3", value: 0, level: 3 },
        { name: "물리 방어력 Lv.4", value: 0, level: 4 },
        { name: "물리 방어력 Lv.5", value: 0, level: 5 },
        { name: "최대 생명력 Lv.1", value: 0, level: 1 },
        { name: "최대 생명력 Lv.2", value: 0, level: 2 },
        { name: "최대 생명력 Lv.3", value: 0, level: 3 },
        { name: "최대 생명력 Lv.4", value: 0, level: 4 },
        { name: "최대 생명력 Lv.5", value: 0, level: 5 }
    ]
    ,
    pants: [
        { name: "아군 강화 Lv.1", atkBuff: 0.96, level: 1 },
        { name: "아군 강화 Lv.2", atkBuff: 1.98, level: 2 },
        { name: "아군 강화 Lv.3", atkBuff: 3, level: 3 },
        { name: "아군 강화 Lv.4", atkBuff: 4.5, level: 4 },
        { name: "아군 강화 Lv.5", atkBuff: 6, level: 5 },
        { name: "추가 피해 Lv.1", finalDamagePer: 1.0038, level: 1 },
        { name: "추가 피해 Lv.2", finalDamagePer: 1.0079, level: 2 },
        { name: "추가 피해 Lv.3", finalDamagePer: 1.012, level: 3 },
        { name: "추가 피해 Lv.4", finalDamagePer: 1.018, level: 4 },
        { name: "추가 피해 Lv.5", finalDamagePer: 1.024, level: 5 },
        { name: "치명타 피해 Lv.1", finalDamagePer: 1.0038, level: 1 },
        { name: "치명타 피해 Lv.2", finalDamagePer: 1.0079, level: 2 },
        { name: "치명타 피해 Lv.3", finalDamagePer: 1.012, level: 3 },
        { name: "치명타 피해 Lv.4", finalDamagePer: 1.018, level: 4 },
        { name: "치명타 피해 Lv.5", finalDamagePer: 1.024, level: 5 },
        { name: "아이덴티티 획득 Lv.1", value: 0, level: 1 },
        { name: "아이덴티티 획득 Lv.2", value: 0, level: 2 },
        { name: "아이덴티티 획득 Lv.3", value: 0, level: 3 },
        { name: "아이덴티티 획득 Lv.4", value: 0, level: 4 },
        { name: "아이덴티티 획득 Lv.5", value: 0, level: 5 }
    ]
    ,
    glove: [
        { name: "회심 Lv.1", finalDamagePer: 1.0023, level: 1 },
        { name: "회심 Lv.2", finalDamagePer: 1.0047, level: 2 },
        { name: "회심 Lv.3", finalDamagePer: 1.0072, level: 3 },
        { name: "회심 Lv.4", finalDamagePer: 1.0108, level: 4 },
        { name: "회심 Lv.5", finalDamagePer: 1.0144, level: 5 },
        { name: "달인 Lv.1", finalDamagePer: 1.0023, level: 1 },
        { name: "달인 Lv.2", finalDamagePer: 1.0047, level: 2 },
        { name: "달인 Lv.3", finalDamagePer: 1.0072, level: 3 },
        { name: "달인 Lv.4", finalDamagePer: 1.0108, level: 4 },
        { name: "달인 Lv.5", finalDamagePer: 1.0144, level: 5 },
        { name: "선봉대 Lv.1", finalDamagePer: 1.0023, level: 1 },
        { name: "선봉대 Lv.2", finalDamagePer: 1.0047, level: 2 },
        { name: "선봉대 Lv.3", finalDamagePer: 1.0072, level: 3 },
        { name: "선봉대 Lv.4", finalDamagePer: 1.0108, level: 4 },
        { name: "선봉대 Lv.5", finalDamagePer: 1.0144, level: 5 },
        { name: "강맹 Lv.1", finalDamagePer: 1.0023, level: 1 },
        { name: "강맹 Lv.2", finalDamagePer: 1.0047, level: 2 },
        { name: "강맹 Lv.3", finalDamagePer: 1.0072, level: 3 },
        { name: "강맹 Lv.4", finalDamagePer: 1.0108, level: 4 },
        { name: "강맹 Lv.5", finalDamagePer: 1.0144, level: 5 },
        { name: "칼날 방패 Lv.1", finalDamagePer: 1.0023, level: 1 },
        { name: "칼날 방패 Lv.2", finalDamagePer: 1.0047, level: 2 },
        { name: "칼날 방패 Lv.3", finalDamagePer: 1.0072, level: 3 },
        { name: "칼날 방패 Lv.4", finalDamagePer: 1.0108, level: 4 },
        { name: "칼날 방패 Lv.5", finalDamagePer: 1.0144, level: 5 },
        { name: "행운 Lv.1", finalDamagePer: 1.0023, level: 1 },
        { name: "행운 Lv.2", finalDamagePer: 1.0047, level: 2 },
        { name: "행운 Lv.3", finalDamagePer: 1.0072, level: 3 },
        { name: "행운 Lv.4", finalDamagePer: 1.0108, level: 4 },
        { name: "행운 Lv.5", finalDamagePer: 1.0144, level: 5 },
        { name: "선각자 Lv.1", value: 0, level: 1 },
        { name: "선각자 Lv.2", value: 0, level: 2 },
        { name: "선각자 Lv.3", value: 0, level: 3 },
        { name: "선각자 Lv.4", value: 0, level: 4 },
        { name: "선각자 Lv.5", value: 0, level: 5 },
        { name: "신념 Lv.1", value: 0, level: 1 },
        { name: "신념 Lv.2", value: 0, level: 2 },
        { name: "신념 Lv.3", value: 0, level: 3 },
        { name: "신념 Lv.4", value: 0, level: 4 },
        { name: "신념 Lv.5", value: 0, level: 5 },
        { name: "진군 Lv.1", value: 0, level: 1 },
        { name: "진군 Lv.2", value: 0, level: 2 },
        { name: "진군 Lv.3", value: 0, level: 3 },
        { name: "진군 Lv.4", value: 0, level: 4 },
        { name: "진군 Lv.5", value: 0, level: 5 }
    ]
}


export let accessoryOptionData = {
    t3RelicData : {
        necklace:[
            { name: "추가 피해 +0.39%", grade: "하", addDamagePer: 0.39 },
            { name: "추가 피해 +0.90%", grade: "중", addDamagePer: 0.9 },
            { name: "추가 피해 +1.50%", grade: "상", addDamagePer: 1.5 },
            { name: "적에게 주는 피해 +0.30%", grade: "하", finalDamagePer: 0.3 },
            { name: "적에게 주는 피해 +0.69%", grade: "중", finalDamagePer: 0.69 },
            { name: "적에게 주는 피해 +1.15%", grade: "상", finalDamagePer: 1.15 },
            { name: "낙인력 +1.20%", grade: "하", stigmaPer: 1.2 },
            { name: "낙인력 +2.76%", grade: "중", stigmaPer: 2.76 },
            { name: "낙인력 +4.60%", grade: "상", stigmaPer: 4.6 },
            { name: "세레나데, 신앙, 조화 게이지 획득량 +0.90%", grade: "하", value: 0 },
            { name: "세레나데, 신앙, 조화 게이지 획득량 +2.07%", grade: "중", value: 0 },
            { name: "세레나데, 신앙, 조화 게이지 획득량 +3.45%", grade: "상", value: 0 },
        ],
        earing:[
            { name: "무기 공격력 +0.46%", grade: "하", weaponAtkPer: 0.46 },
            { name: "무기 공격력 +1.04%", grade: "중", weaponAtkPer: 1.04 },
            { name: "무기 공격력 +1.72%", grade: "상", weaponAtkPer: 1.72 },
            { name: "공격력 +0.24%", grade: "하", atkPer: 0.24 },
            { name: "공격력 +0.54%", grade: "중", atkPer: 0.54 },
            { name: "공격력 +0.89%", grade: "상", atkPer: 0.89 },
            { name: "파티원 회복 효과 +0.54%", grade: "하", value: 0 },
            { name: "파티원 회복 효과 +1.21%", grade: "중", value: 0 },
            { name: "파티원 회복 효과 +2.01%", grade: "상", value: 0 },
            { name: "파티원 보호막 효과 +0.54%", grade: "하", value: 0 },
            { name: "파티원 보호막 효과 +1.21%", grade: "중", value: 0 },
            { name: "파티원 보호막 효과 +2.01%", grade: "상", value: 0 },
        ],
        ring:[
            { name: "치명타 적중률 +0.24%", grade: "하", criticalChancePer: 0.24 },
            { name: "치명타 적중률 +0.54%", grade: "중", criticalChancePer: 0.54 },
            { name: "치명타 적중률 +0.89%", grade: "상", criticalChancePer: 0.89 },
            { name: "치명타 피해 +0.61%", grade: "하", criticalDamagePer: 0.61 },
            { name: "치명타 피해 +1.38%", grade: "중", criticalDamagePer: 1.38 },
            { name: "치명타 피해 +2.30%", grade: "상", criticalDamagePer: 2.3 },
            { name: "아군 공격력 강화 효과 +0.76%", grade: "하", atkBuff: 0.76 },
            { name: "아군 공격력 강화 효과 +1.72%", grade: "중", atkBuff: 1.72 },
            { name: "아군 공격력 강화 효과 +2.88%", grade: "상", atkBuff: 2.88 },
            { name: "아군 피해량 강화 효과 +1.14%", grade: "하", damageBuff: 1.14 },
            { name: "아군 피해량 강화 효과 +2.58%", grade: "중", damageBuff: 2.58 },
            { name: "아군 피해량 강화 효과 +4.32%", grade: "상", damageBuff: 4.32 },
        ],
        common:[
            { name: "공격력 +14", grade: "하", atkPlus:14 },
            { name: "공격력 +33", grade: "중", atkPlus:33 },
            { name: "공격력 +68", grade: "상", atkPlus:68 },
            { name: "무기 공격력 +32", grade: "하", weaponAtkPlus: 32 },
            { name: "무기 공격력 +75", grade: "중", weaponAtkPlus: 75 },
            { name: "무기 공격력 +155", grade: "상", weaponAtkPlus: 155 },
            { name: "최대 생명력 +719", grade: "하", value: 0 },
            { name: "최대 생명력 +1654", grade: "중", value: 0 },
            { name: "최대 생명력 +2756", grade: "상", value: 0 },
            { name: "최대 마나 +5", grade: "하", value: 0 },
            { name: "최대 마나 +10", grade: "중", value: 0 },
            { name: "최대 마나 +17", grade: "상", value: 0 },
        ]
    },

    t3MythicData : {
        necklace:[
            { name: "추가 피해 +0.48%", grade: "하", addDamagePer: 0.48 },
            { name: "추가 피해 +1.09%", grade: "중", addDamagePer: 1.09 },
            { name: "추가 피해 +1.82%", grade: "상", addDamagePer: 1.82 },
            { name: "적에게 주는 피해 +0.37%", grade: "하", finalDamagePer: 0.37 },
            { name: "적에게 주는 피해 +0.84%", grade: "중", finalDamagePer: 0.84 },
            { name: "적에게 주는 피해 +1.40%", grade: "상", finalDamagePer: 1.4 },
            { name: "낙인력 +1.48%", grade: "하", stigmaPer: 1.48 },
            { name: "낙인력 +3.36%", grade: "중", stigmaPer: 3.36 },
            { name: "낙인력 +5.60%", grade: "상", stigmaPer: 5.6 },
            { name: "세레나데, 신앙, 조화 게이지 획득량 +1.48%", grade: "하", value: 0 },
            { name: "세레나데, 신앙, 조화 게이지 획득량 +3.36%", grade: "중", value: 0 },
            { name: "세레나데, 신앙, 조화 게이지 획득량 +5.60%", grade: "상", value: 0 },

        ],
        earing:[
            { name: "무기 공격력 +0.56%", grade: "하", weaponAtkPer: 0.56 },
            { name: "무기 공격력 +1.26%", grade: "중", weaponAtkPer: 1.26 },
            { name: "무기 공격력 +2.10%", grade: "상", weaponAtkPer: 2.1 },
            { name: "공격력 +0.29%", grade: "하", atkPer: 0.29 },
            { name: "공격력 +0.66%", grade: "중", atkPer: 0.66 },
            { name: "공격력 +1.09%", grade: "상", atkPer: 1.09 },
            { name: "파티원 회복 효과 +0.65%", grade: "하", value: 0 }, 
            { name: "파티원 회복 효과 +1.47%", grade: "중", value: 0 },
            { name: "파티원 회복 효과 +2.45%", grade: "상", value: 0 },
            { name: "파티원 보호막 효과 +0.65%", grade: "하", value: 0 },
            { name: "파티원 보호막 효과 +1.47%", grade: "중", value: 0 },
            { name: "파티원 보호막 효과 +2.45%", grade: "상", value: 0 },

        ],
        ring:[
            { name: "치명타 적중률 +0.29%", grade: "하", criticalChancePer: 0.29 },
            { name: "치명타 적중률 +0.66%", grade: "중", criticalChancePer: 0.66 },
            { name: "치명타 적중률 +1.09%", grade: "상", criticalChancePer: 1.09 },
            { name: "치명타 피해 +0.74%", grade: "하", criticalDamagePer: 0.74 },
            { name: "치명타 피해 +1.70%", grade: "중", criticalDamagePer: 1.7 },
            { name: "치명타 피해 +2.82%", grade: "상", criticalDamagePer: 2.82 },
            { name: "아군 공격력 강화 효과 +0.92%", grade: "하", atkBuff: 0.92 },
            { name: "아군 공격력 강화 효과 +2.12%", grade: "중", atkBuff: 2.12 },
            { name: "아군 공격력 강화 효과 +3.52%", grade: "상", atkBuff: 3.52 },
            { name: "아군 피해량 강화 효과 +1.38%", grade: "하", damageBuff: 1.38 },
            { name: "아군 피해량 강화 효과 +3.18%", grade: "중", damageBuff: 3.18 },
            { name: "아군 피해량 강화 효과 +5.28%", grade: "상", damageBuff: 5.28 },
        ],
        common:[
            { name: "공격력 +24", grade: "하", atkPlus:24 },
            { name: "공격력 +61", grade: "중", atkPlus:61 },
            { name: "공격력 +118", grade: "상", atkPlus:118 },
            { name: "무기 공격력 +57", grade: "하", weaponAtkPlus: 57 },
            { name: "무기 공격력 +147", grade: "중", weaponAtkPlus: 147 },
            { name: "무기 공격력 +285", grade: "상", weaponAtkPlus: 285 },
            { name: "최대 생명력 +992", grade: "하", value: 0 },
            { name: "최대 생명력 +2253", grade: "중", value: 0 },
            { name: "최대 생명력 +3755", grade: "상", value: 0 },
            { name: "최대 마나 +6", grade: "하", value: 0 },
            { name: "최대 마나 +13", grade: "중", value: 0 },
            { name: "최대 마나 +21", grade: "상", value: 0 },
        ]
    },

    t4Data : {
        necklace:[
            { name: "추가 피해 +0.70%", grade: "하", addDamagePer: 0.7 },
            { name: "추가 피해 +1.60%", grade: "중", addDamagePer: 1.6 },
            { name: "추가 피해 +2.60%", grade: "상", addDamagePer: 2.6 },
            { name: "적에게 주는 피해 +0.55%", grade: "하", finalDamagePer: 0.55 },
            { name: "적에게 주는 피해 +1.20%", grade: "중", finalDamagePer: 1.2 },
            { name: "적에게 주는 피해 +2.00%", grade: "상", finalDamagePer: 2.0 },
            { name: "낙인력 +2.15%", grade: "하", stigmaPer: 2.15 },
            { name: "낙인력 +4.80%", grade: "중", stigmaPer: 4.8 },
            { name: "낙인력 +8.00%", grade: "상", stigmaPer: 8.0 },
            { name: "세레나데, 신앙, 조화 게이지 획득량 +1.60%", grade: "하", value: 0 },
            { name: "세레나데, 신앙, 조화 게이지 획득량 +3.60%", grade: "중", value: 0 },
            { name: "세레나데, 신앙, 조화 게이지 획득량 +6.00%", grade: "상", value: 0 },
        ],
        earing:[
            { name: "무기 공격력 +0.70%", grade: "하", weaponAtkPer: 0.7 },     
            { name: "무기 공격력 +1.60%", grade: "중", weaponAtkPer: 1.6 },
            { name: "무기 공격력 +2.60%", grade: "상", weaponAtkPer: 2.6 },
            { name: "공격력 +0.40%", grade: "하", atkPer: 0.4 },
            { name: "공격력 +0.95%", grade: "중", atkPer: 0.95 },
            { name: "공격력 +1.55%", grade: "상", atkPer: 1.55 },
            { name: "파티원 회복 효과 +0.95%", grade: "하", value: 0 },
            { name: "파티원 회복 효과 +2.10%", grade: "중", value: 0 },
            { name: "파티원 회복 효과 +3.50%", grade: "상", value: 0 },
            { name: "파티원 보호막 효과 +0.95%", grade: "하", value: 0 },
            { name: "파티원 보호막 효과 +2.10%", grade: "중", value: 0 },
            { name: "파티원 보호막 효과 +3.50%", grade: "상", value: 0 },
        ],
        ring:[
            { name: "치명타 적중률 +0.40%", grade: "하", criticalChancePer: 0.4 },
            { name: "치명타 적중률 +0.95%", grade: "중", criticalChancePer: 0.95 },
            { name: "치명타 적중률 +1.55%", grade: "상", criticalChancePer: 1.55 },
            { name: "치명타 피해 +1.10%", grade: "하", criticalDamagePer: 1.1 },
            { name: "치명타 피해 +2.40%", grade: "중", criticalDamagePer: 2.4 },
            { name: "치명타 피해 +4.00%", grade: "상", criticalDamagePer: 4.0 },
            { name: "아군 공격력 강화 효과 +1.35%", grade: "하", atkBuff: 1.35 },
            { name: "아군 공격력 강화 효과 +3.00%", grade: "중", atkBuff: 3.0 },
            { name: "아군 공격력 강화 효과 +5.00%", grade: "상", atkBuff: 5.0 },
            { name: "아군 피해량 강화 효과 +2.00%", grade: "하", damageBuff: 2.0 },
            { name: "아군 피해량 강화 효과 +4.50%", grade: "중", damageBuff: 4.5 },
            { name: "아군 피해량 강화 효과 +7.50%", grade: "상", damageBuff: 7.5 },
        ],
        common:[
            { name: "공격력 +80", grade: "하", atkPlus:80 },
            { name: "공격력 +195", grade: "중", atkPlus:195 },
            { name: "공격력 +390", grade: "상", atkPlus:390 },
            { name: "무기 공격력 +195", grade: "하", weaponAtkPlus: 195 },
            { name: "무기 공격력 +480", grade: "중", weaponAtkPlus: 480 },
            { name: "무기 공격력 +960", grade: "상", weaponAtkPlus: 960 },
            { name: "최대 생명력 +1300", grade: "하", value: 0 },
            { name: "최대 생명력 +3250", grade: "중", value: 0 },
            { name: "최대 생명력 +6500", grade: "상", value: 0 },
            { name: "최대 마나 +6", grade: "하", value: 0 },
            { name: "최대 마나 +15", grade: "중", value: 0 },
            { name: "최대 마나 +30", grade: "상", value: 0 },
        ]
    }




}